export const requiredFieldsByResource = {
  cidadaos: ["nome", "fregCidadao", "nrTelemovel", "email"],
  municipios: ["nome"],
  equipas: ["especializacao", "fregEquipa"],
  trabalhadores: [
    "nomeTrabalhador",
    "emailTrabalhador",
    "telemovelTrabalhador",
    "idFreguesia",
  ],
  recursos: ["tipo", "estado", "localizacao", "equipaResponsavel"],
  ocorrencias: [
    "descricao",
    "localizacao",
    "dataOcorrencia",
    "nomeAutor",
    "nrTelemovelAutor",
    "severidade",
    "estado",
    "idCidadao",
    "idFreguesia",
    "tipo_ocorrencia",
  ],
  mensagens: ["texto", "dataMensagem", "idCidadao", "idOcorrencia"],
};
