export const FREGUESIAS = [
  'Todas',
  'Árvore',
  'Aveleda',
  'Azurara',
  'Fajozes',
  'Gião',
  'Guilhabreu',
  'Junqueira',
  'Labruge',
  'Macieira da Maia',
  'Mindelo',
  'Modivas',
  'Vila Chã',
  'Vila do Conde',
  'Vilar de Pinheiro',
  'Bagunte, Ferreiró, Outeiro Maior e Parada',
  'Touguinha e Touguinhó',
  'Vilar e Mosteiró',
  'Malta',
  'Canidelo',
  'Fornelo',
  'Vairão',
  'Retorta',
  'Tougues',
  'Rio Mau',
  'Arcos',
  'Argivai',
]

export default FREGUESIAS
